// File: adder.v
// Generated by MyHDL 0.10
// Date: Mon Nov 19 13:42:22 2018


`timescale 1ns/10ps

module adder (
    A,
    B,
    output2,
    clk,
    reset
);
// :param A:  input
// :param B: input
// :param output2: output
// :param clk:
// :param reset:
// :return:

input signed [15:0] A;
input signed [15:0] B;
output signed [15:0] output2;
reg signed [15:0] output2;
input clk;
input reset;




always @(posedge clk, negedge reset) begin: ADDER_SEQ
    if (reset == 0) begin
        output2 <= 0;
    end
    else begin
        output2 <= (A + B);
    end
end

endmodule
