-- File: my_mul.vhd
-- Generated by MyHDL 0.10
-- Date: Tue Nov 27 19:19:09 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity my_mul is
    port (
        a: in signed (9 downto 0);
        b: in signed (11 downto 0);
        c: out signed (20 downto 0)
    );
end entity my_mul;


architecture MyHDL of my_mul is



begin





c <= resize(a * b, 21);

end architecture MyHDL;
