-- File: adder.vhd
-- Generated by MyHDL 0.10
-- Date: Mon Nov 19 13:29:22 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity adder is
    port (
        A: in signed (15 downto 0);
        B: in signed (15 downto 0);
        output2: out signed (15 downto 0);
        clk: in std_logic;
        reset: in std_logic
    );
end entity adder;


architecture MyHDL of adder is



begin




ADDER_SEQ: process (clk, reset) is
begin
    if (reset = '0') then
        output2 <= to_signed(7208, 16);
    elsif rising_edge(clk) then
        output2 <= (A + B);
    end if;
end process ADDER_SEQ;

end architecture MyHDL;
